name: Continuous Integration (CI)

on: [push, pull_request] # Triggers on push AND pull_request (best practice)

jobs:
  # JOB 1: Build and Test the Java Backend
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build and Test with Maven (with JaCoCo)
        run: mvn clean verify --file api/pom.xml # <- Use the correct path to your POM!
        # The 'verify' phase runs the tests. JaCoCo is automatically triggered by the Maven lifecycle.

      # NEW STEP: Upload JaCoCo Coverage Report
      - name: Upload JaCoCo coverage report
        if: always() # Upload the report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: api/target/site/jacoco/ # <- The path where JaCoCo generates the HTML report. UPDATE THE PATH!
          retention-days: 5

  # JOB 2: Build and Test the Angular Frontend
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: front/package-lock.json # NOTE: Path changed to 'front/'

      - name: Install dependencies (CI)
        run: npm ci
        working-directory: ./front # NOTE: Path changed to 'front/' (no 'end')

      # -- LINTING STEP REMOVED --

      - name: Run Tests (Headless)
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./front # NOTE: Path changed to 'front/'

      - name: Build for production
        run: npm run build -- --configuration production
        working-directory: ./front # NOTE: Path changed to 'front/'
