name: Debug Secrets Test

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug-secrets:
    name: Test Secret Access
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Secrets via Environment Variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "=== Testing Secret Access ==="

          # Test Docker Hub Username
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "❌ DOCKER_HUB_USERNAME is empty or not accessible"
          else
            echo "✅ DOCKER_HUB_USERNAME is accessible (length: ${#DOCKER_USERNAME} chars)"
          fi

          # Test Docker Hub Token
          if [ -z "$DOCKER_TOKEN" ]; then
            echo "❌ DOCKER_HUB_TOKEN is empty or not accessible"
          else
            echo "✅ DOCKER_HUB_TOKEN is accessible (length: ${#DOCKER_TOKEN} chars)"
          fi

          # Test Sonar Token
          if [ -z "$SONAR_TOKEN" ]; then
            echo "❌ SONAR_TOKEN is empty or not accessible"
          else
            echo "✅ SONAR_TOKEN is accessible (length: ${#SONAR_TOKEN} chars)"
          fi

          echo ""
          echo "=== Context Information ==="
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"

      - name: Test Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_TOKEN" ]; then
            echo "Attempting Docker Hub login..."
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
            if [ $? -eq 0 ]; then
              echo "✅ Docker login successful!"
              docker logout
            else
              echo "❌ Docker login failed!"
            fi
          else
            echo "⚠️ Skipping Docker login test - secrets not available"
          fi
