name: Debug Secrets Test

on:
  workflow_dispatch: # Manual trigger only for testing

jobs:
  debug-secrets:
    name: Debug Secrets Access
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets (Safe Version)
        run: |
          echo "Testing secret access..."

          # Test if secrets exist (without exposing values)
          if [ -n "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "✅ DOCKER_HUB_USERNAME secret is accessible"
            echo "Username length: ${#DOCKER_USERNAME} characters"
          else
            echo "❌ DOCKER_HUB_USERNAME secret is NOT accessible"
          fi

          if [ -n "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo "✅ DOCKER_HUB_TOKEN secret is accessible"
            echo "Token length: ${#DOCKER_TOKEN} characters"
          else
            echo "❌ DOCKER_HUB_TOKEN secret is NOT accessible"
          fi

          if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "✅ SONAR_TOKEN secret is accessible"
          else
            echo "❌ SONAR_TOKEN secret is NOT accessible"
          fi

          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Test Docker Login (if secrets work)
        if: ${{ secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
