- name: Validate Docker Hub Credentials
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  run: |
    if [ -z "$DOCKER_USERNAME" ]; then
      echo "❌ DOCKER_HUB_USERNAME secret is not accessible"
      exit 1
    fi
    if [ -z "$DOCKER_TOKEN" ]; then
      echo "❌ DOCKER_HUB_TOKEN secret is not accessible"  
      exit 1
    fi
    echo "✅ Docker Hub credentials are configured"
    echo "Username: $DOCKER_USERNAME"

- name: Login to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    password: ${{ secrets.DOCKER_HUB_TOKEN }}