name: DockerHub Credentials Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-dockerhub-access:
    name: Test DockerHub Credentials
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Docker Hub Credentials
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "Testing Docker Hub credentials..."

          if [ -z "$DOCKER_USERNAME" ]; then
            echo "❌ DOCKER_HUB_USERNAME is missing"
            exit 1
          else
            echo "✅ DOCKER_HUB_USERNAME found: $DOCKER_USERNAME"
          fi

          if [ -z "$DOCKER_TOKEN" ]; then
            echo "❌ DOCKER_HUB_TOKEN is missing"
            exit 1
          else
            echo "✅ DOCKER_HUB_TOKEN found (length: ${#DOCKER_TOKEN} chars)"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Verify Login
        run: |
          echo "✅ Docker Hub login successful!"
          docker logout
